apiVersion: v1
kind: Pod
metadata:
  name: busybox-poc-net
  labels:
    app: demo-labels
    net-group: poc-epg
    network: poc-net
spec:
  containers:
  - name: bbox
    image: contiv/nc-busybox
    command:
      - sleep
      - "7200"

